### ISSUE TITLE
E1072 with recent vim versions

### ISSUE THREAD

**Issue by blues0024** [puremourning/vimspector#546] opened 2022-03-08 09:49 UTC
### Description

When I tried to run the following command "VimspectorInstall [something]" in my vim with MacOS, I found the following error (sorry for a little Korean, not significant). This does not happened when I run it on Linux (Ubuntu). I wonder why this happen, and please anybody give me the solution.

function vimspector#Install[5]..function vimspector#Install 수행중 에러 발견:
   5 줄:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/installer.py", line 182, in RunInstaller
    OUTPUT_VIEW.RunJobWithOutput( 'Installer',
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/output.py", line 164, in RunJobWithOutput
    self._CreateBuffer( category, cmd = cmd, **kwargs )
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/output.py", line 193, in _CreateBuffer
    out = utils.SetUpCommandBuffer(
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/utils.py", line 101, in SetUpCommandBuffer
    buf = Call( f'vimspector#internal#{api_prefix}job#StartCommandWithLog',
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/utils.py", line 739, in Call
    return vim.eval( call )
vim.error: Vim(return):E1072: Cannot compare bool with special

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc`
2. Open any projects...
3. Run 'VimspectorInstall [something]'. All debugers are possible for [somthing].

### Expected Behaviour

Debugging, or completely installed debuggers through "VimspectorInstall" command.

### Actual Behaviour

Following error occured:
function vimspector#Install[5]..function vimspector#Install 수행중 에러 발견:
   5 줄:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/installer.py", line 182, in RunInstaller
    OUTPUT_VIEW.RunJobWithOutput( 'Installer',
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/output.py", line 164, in RunJobWithOutput
    self._CreateBuffer( category, cmd = cmd, **kwargs )
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/output.py", line 193, in _CreateBuffer
    out = utils.SetUpCommandBuffer(
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/utils.py", line 101, in SetUpCommandBuffer
    buf = Call( f'vimspector#internal#{api_prefix}job#StartCommandWithLog',
  File "/Users/seulwoo/.vim/pack/vimspector/opt/vimspector/python3/vimspector/utils.py", line 739, in Call
    return vim.eval( call )
vim.error: Vim(return):E1072: Cannot compare bool with special

### Additional information

Occured error for both Plugin Manager and tar.

### Installation Type

Plugin Manager (git clone)

### Vimspector version

193900387

### Vim version

```Text
VIM - Vi IMproved 8.2 (2019 Dec 12, 빌드한 날짜 Mar 03 2022 17:05:35)
macOS 버젼 - x86_64
포함된 패치: 1-4500
```

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment] 2022-03-08 16:50
Thanks for the report, I can reproduce. It looks like a recent Vim change has caused this. I'll look into it.

**Comment by puremourning** [comment] 2022-03-08 17:28
This was broken by https://github.com/vim/vim/commit/7a2222487507eb13cccdb9a66397092775d62b8c, though I can't seem to work out exactly why. It seems kind of inconsistent, and finding a minimal repro is not trivial.

**Comment by puremourning** [comment] 2022-03-08 19:22
I've minimally reproduced this and raised https://github.com/vim/vim/issues/9910

**Comment by puremourning** [comment] 2022-03-08 19:55
should be fixed now. please update. thanks again for the report.

**Closed** 2022-03-08 19:55 UTC

**Comment by blues0024** [comment] 2022-03-14 00:49
@puremourning It working! Thanks very much!
