### ISSUE TITLE
[Feature Request]: Automatically create files .vimspector.json

### ISSUE THREAD

**Issue by thevan96** [puremourning/vimspector#349] opened 2021-02-17 10:16 UTC
every time i debug i have to mess around configuring the .vimspector file. You can add a function to create the .vimspector file yourself

**Comment by puremourning** [comment] 2021-02-17 12:21
This is a low-effort duplicate of https://github.com/puremourning/vimspector/issues/270

You can also create your configurations once in a central location (see the docs for details).

**Closed** 2021-02-17 12:20 UTC

**Comment by puremourning** [comment] 2021-02-17 13:53
https://puremourning.github.io/vimspector/configuration.html#debug-configurations

I use this a lot. Here are some of mine for home (I have many more for work): https://github.com/puremourning/.vim-mac/tree/master/vimspector-conf/configurations/macos

**Comment by thevan96** [comment] 2021-02-25 05:25
Thank you
