### ISSUE TITLE
[Feature Request]: Console commands history

### ISSUE THREAD

**Issue by eyalz800** [puremourning/vimspector#262] opened 2020-09-24 21:37 UTC
I wish there was a way inside the vimspector console window in insert mode to bind some key to browse the previous commands. Like Up/C-r in the terminal.

Other than that I feel this is an awesome plugin and it already improved my workflow by far.

**Comment by puremourning** [comment] 2020-09-24 22:28
I think this is a duplicate of https://github.com/puremourning/vimspector/issues/52

But in short this is a limitation of prompt buffers (it’s in :help todo). It’s possible to do something out of band but probably hard and not good.

**Closed by puremourning** 2020-09-24 22:28 UTC
