### ISSUE TITLE
Raise error when add variables to inspect with C++ vscode-cpptools

### ISSUE THREAD

**Issue by codycjy** [puremourning/vimspector#616] opened 2022-07-10 08:12 UTC
### Description

This is my code  
```cpp
#include<iostream>
#include<vector>
#include<queue>
using namespace std;
int T,N;
int ans[5<<17];
vector<pair<int,int> >G[5<<17];
int main()
{
	ios::sync_with_stdio(false);
	cin.tie(nullptr);
	cin>>T;
	for(;T--;)
	{
		cin>>N;
		for(int i=1;i<=N;i++)G[i].clear();
		for(int i=1;i<=N;i++)
		{
			int B;cin>>B;
			int l=i/(B+1)+1;
			int r=B==0?N:i/B;
			G[l].push_back(make_pair(-r,i));
		}
		priority_queue<pair<int,int> >Q;
		for(int i=1;i<=N;i++)
		{
			for(pair<int,int>p:G[i])
			{
				Q.push(p);
			}
			pair<int,int>now=Q.top();Q.pop();
			ans[now.second-1]=i;
		}
		for(int i=0;i<N;i++)cout<<ans[i]<<" \n"[i+1==N];
	}
}
```

When I Start debugging and try to add variables like _G_ , _ans_ and so on the error appears.
This bug appears at neovim with the minimal reproduction.
Due to my vim version is 8.1 so I can't sure whether this bug exists in 8.2 or higher, but when I test it, the error reproduced.

### Works in vim?

Only broken in Neovim

### Works with clean config?

Yes

### Minimal Reproduction

List of steps to reproduce:

1. Run `/usr/bin/nvim --clean  -Nu /home/saltfish/.nvim/plugged/vimspector/tests/vimrc --cmd "let g:vimspector_enable_mappings='HUMAN'" test.cpp
`
2. Open the file in the empty folder just the single cpp file and  the`.vimspector.json` below
  add breakpoints at line 22 and 32
```json
{
  "configurations": {
    "Launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "request": "launch",
        "type": "cppdbg",
        "MIMode":"gdb",
        "filetypes": [ "cpp", "c", "objc", "rust" ],
        "program": "${fileDirname}/${fileBasenameNoExtension}",
        "cwd": "${workspaceFolder}",
        "externalConsole": true,
        "preLaunchTask":"build",
        "setupCommands":[
                {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                
                }
        ]
      }
    }
  }
}
```

  compile the test file with`g++ test.cpp -o test -ggdb -std=c++17`

3. Press F5 to run the debug.
  add variable _ans_ or _G_ to the  vimspector.Variables

### Expected Behaviour

Press F5 start the debug and add a variable to inspect.

### Actual Behaviour
When I input the variable name and press Enter, Raise following error

> Error detected while processing function vimspector#AddWatchPrompt[6]..vimspector#AddWatch[16]..provider#python3#Call:                                                                                                                                            
> line   18:
> Error invoking 'python_execute' on channel 6 (python3-script-host):
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/saltfish/.nvim/plugged/vimspector/python3/vimspector/debug_session.py", line 433, in wrapper
>     return fct( self, *args, **kwargs )
>   File "/home/saltfish/.nvim/plugged/vimspector/python3/vimspector/debug_session.py", line 776, in AddWatch
>     self._variablesView.AddWatch( self._stackTraceView.GetCurrentFrame(),
>   File "/home/saltfish/.nvim/plugged/vimspector/python3/vimspector/variables.py", line 501, in AddWatch
>     self.EvaluateWatches( frame )
>   File "/home/saltfish/.nvim/plugged/vimspector/python3/vimspector/variables.py", line 527, in EvaluateWatches
>     watch.SetCurrentFrame( current_frame )
>   File "/home/saltfish/.nvim/plugged/vimspector/python3/vimspector/variables.py", line 181, in SetCurrentFrame
>     self.expression[ 'frameId' ] = frame[ 'id' ]
> TypeError: 'NoneType' object is not subscriptable

### Additional information

  Using `g++ --version` output `g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`

### Installation Type

Plugin Manager (git clone)

### Vimspector version

bdfa7471ec63e49b7712a8f16ee7d1f96f3783d8

### Debug Info

```Text
Vimspector Debug Info
--------------------------------------------------------------------------------
ConnectionType: neojob
Adapter: 
--------------------------------------------------------------------------------
{
  "attach": {
    "pidProperty": "processId",
    "pidSelect": "ask"
  },
  "command": [
    "/home/saltfish/.nvim/plugged/vimspector/gadgets/linux/vscode-cpptools/debugAdapters/bin/OpenDebugAD7"
  ],
  "configuration": {
    "args": [],
    "cwd": "/home/saltfish/TestEnv",
    "environment": [],
    "type": "cppdbg"
  },
  "name": "cppdbg",
  "env": {},
  "cwd": "/home/saltfish/TestEnv"
}
--------------------------------------------------------------------------------
Configuration: 
--------------------------------------------------------------------------------
{
  "adapter": "vscode-cpptools",
  "configuration": {
    "request": "launch",
    "type": "cppdbg",
    "MIMode": "gdb",
    "filetypes": [
      "cpp",
      "c",
      "objc",
      "rust"
    ],
    "program": "/home/saltfish/TestEnv/test",
    "cwd": "/home/saltfish/TestEnv",
    "externalConsole": true,
    "preLaunchTask": "build",
    "setupCommands": [
      {
        "description": "Enable pretty-printing for gdb",
        "text": "-enable-pretty-printing",
        "ignoreFailures": true
      }
    ]
  }
}
--------------------------------------------------------------------------------
API Prefix: neo
Launch/Init: True / True
Workspace Root: /home/saltfish/TestEnv
Launch Config: 
--------------------------------------------------------------------------------
{
  "args": [],
  "cwd": "/home/saltfish/TestEnv",
  "environment": [],
  "type": "cppdbg",
  "request": "launch",
  "MIMode": "gdb",
  "filetypes": [
    "cpp",
    "c",
    "objc",
    "rust"
  ],
  "program": "/home/saltfish/TestEnv/test",
  "externalConsole": true,
  "preLaunchTask": "build",
  "setupCommands": [
    {
      "description": "Enable pretty-printing for gdb",
      "text": "-enable-pretty-printing",
      "ignoreFailures": true
    }
  ],
  "name": "test"
}
--------------------------------------------------------------------------------
Server Capabilities: 
--------------------------------------------------------------------------------
{
  "supportsConfigurationDoneRequest": true,
  "supportsFunctionBreakpoints": true,
  "supportsConditionalBreakpoints": true,
  "supportsEvaluateForHovers": true,
  "exceptionBreakpointFilters": [
    {
      "filter": "all",
      "label": "All C++ Exceptions",
      "default": false,
      "supportsCondition": true,
      "conditionDescription": "std::out_of_range,std::invalid_argument"
    }
  ],
  "supportsSetVariable": true,
  "supportsGotoTargetsRequest": true,
  "supportsCompletionsRequest": true,
  "completionTriggerCharacters": [],
  "supportsModulesRequest": true,
  "supportedChecksumAlgorithms": [],
  "supportsValueFormattingOptions": true,
  "supportsLogPoints": true,
  "supportsSetExpression": true,
  "supportsDataBreakpoints": true,
  "supportsReadMemoryRequest": true,
  "supportsDisassembleRequest": true,
  "supportsClipboardContext": true,
  "supportsSteppingGranularity": true,
  "supportsInstructionBreakpoints": true,
  "supportsExceptionFilterOptions": true
}
--------------------------------------------------------------------------------
Line Breakpoints: 
--------------------------------------------------------------------------------
{
  "/home/saltfish/TestEnv/test.cpp": [
    {
      "state": "ENABLED",
      "line": 22,
      "options": {},
      "sign_id": 1,
      "server_bp": {
        "id": 1,
        "verified": true,
        "line": 22,
        "BoundBreakpoints": []
      }
    },
    {
      "state": "ENABLED",
      "line": 32,
      "options": {},
      "sign_id": 3,
      "server_bp": {
        "id": 2,
        "verified": true,
        "line": 32,
        "BoundBreakpoints": []
      }
    }
  ]
}
--------------------------------------------------------------------------------
Func Breakpoints: 
--------------------------------------------------------------------------------
[]
--------------------------------------------------------------------------------
Ex Breakpoints: 
--------------------------------------------------------------------------------
{
  "filters": []
}
--------------------------------------------------------------------------------

```

### Log file

```Text
2022-07-11 14:33:37,251 - INFO - **** INITIALISING NEW VIMSPECTOR SESSION ****
2022-07-11 14:33:37,251 - INFO - API is: neo
2022-07-11 14:33:37,251 - INFO - VIMSPECTOR_HOME = /home/saltfish/.nvim/plugged/vimspector/python3/vimspector/../..
2022-07-11 14:33:37,255 - INFO - gadgetDir = /home/saltfish/.nvim/plugged/vimspector/gadgets/linux
2022-07-11 14:33:40,678 - INFO - User requested start debug session with {}
2022-07-11 14:33:40,681 - DEBUG - Reading configurations from: None
2022-07-11 14:33:40,682 - DEBUG - Reading configurations from: /home/saltfish/TestEnv/.vimspector.json
2022-07-11 14:33:40,684 - DEBUG - Reading gadget config: /home/saltfish/.nvim/plugged/vimspector/gadgets/linux/.gadgets.json
2022-07-11 14:33:40,702 - DEBUG - Reading gadget config: None
2022-07-11 14:33:40,702 - INFO - Configuration: {"adapter": "vscode-cpptools", "configuration": {"request": "launch", "type": "cppdbg", "MIMode": "gdb", "filetypes": ["cpp", "c", "objc", "rust"], "program": "/home/saltfish/TestEnv/test", "cwd": "/home/saltfish/TestEnv", "externalConsole": true, "preLaunchTask": "build", "setupCommands": [{"description": "Enable pretty-printing for gdb", "text": "-enable-pretty-printing", "ignoreFailures": true}]}}
2022-07-11 14:33:40,702 - INFO - Adapter: {"attach": {"pidProperty": "processId", "pidSelect": "ask"}, "command": ["/home/saltfish/.nvim/plugged/vimspector/gadgets/linux/vscode-cpptools/debugAdapters/bin/OpenDebugAD7"], "configuration": {"args": [], "cwd": "/home/saltfish/TestEnv", "environment": [], "type": "cppdbg"}, "name": "cppdbg"}
2022-07-11 14:33:40,704 - DEBUG - min_width/height: 149/50, actual: 264/63 - result: horizontal
2022-07-11 14:33:40,760 - DEBUG - LAUNCH!
2022-07-11 14:33:40,763 - INFO - Starting debug adapter with: {"attach": {"pidProperty": "processId", "pidSelect": "ask"}, "command": ["/home/saltfish/.nvim/plugged/vimspector/gadgets/linux/vscode-cpptools/debugAdapters/bin/OpenDebugAD7"], "configuration": {"args": [], "cwd": "/home/saltfish/TestEnv", "environment": [], "type": "cppdbg"}, "name": "cppdbg"}
2022-07-11 14:33:40,763 - DEBUG - Connection Type: neojob
2022-07-11 14:33:40,767 - INFO - Debug Adapter Started
2022-07-11 14:33:40,768 - DEBUG - Sending Message: {"command": "initialize", "arguments": {"adapterID": "cppdbg", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true, "supportsMemoryReferences": true}, "seq": 0, "type": "request"}
2022-07-11 14:33:41,265 - DEBUG - Message received: {'type': 'response', 'request_seq': 0, 'success': True, 'command': 'initialize', 'body': {'supportsConfigurationDoneRequest': True, 'supportsFunctionBreakpoints': True, 'supportsConditionalBreakpoints': True, 'supportsEvaluateForHovers': True, 'exceptionBreakpointFilters': [{'filter': 'all', 'label': 'All C++ Exceptions', 'default': False, 'supportsCondition': True, 'conditionDescription': 'std::out_of_range,std::invalid_argument'}], 'supportsSetVariable': True, 'supportsGotoTargetsRequest': True, 'supportsCompletionsRequest': True, 'completionTriggerCharacters': [], 'supportsModulesRequest': True, 'supportedChecksumAlgorithms': [], 'supportsValueFormattingOptions': True, 'supportsLogPoints': True, 'supportsSetExpression': True, 'supportsDataBreakpoints': True, 'supportsReadMemoryRequest': True, 'supportsDisassembleRequest': True, 'supportsClipboardContext': True, 'supportsSteppingGranularity': True, 'supportsInstructionBreakpoints': True, 'supportsExceptionFilterOptions': True}, 'seq': 1}
2022-07-11 14:33:41,266 - DEBUG - Sending Message: {"command": "launch", "arguments": {"args": [], "cwd": "/home/saltfish/TestEnv", "environment": [], "type": "cppdbg", "request": "launch", "MIMode": "gdb", "filetypes": ["cpp", "c", "objc", "rust"], "program": "/home/saltfish/TestEnv/test", "externalConsole": true, "preLaunchTask": "build", "setupCommands": [{"description": "Enable pretty-printing for gdb", "text": "-enable-pretty-printing", "ignoreFailures": true}], "name": "test"}, "seq": 1, "type": "request"}
2022-07-11 14:33:41,354 - DEBUG - Message received: {'type': 'request', 'command': 'runInTerminal', 'arguments': {'kind': 'external', 'title': 'cppdbg: test', 'cwd': '', 'args': ['/bin/sh', '/tmp/Microsoft-MIEngine-Cmd-xf0lzres.4df'], 'env': {}}, 'seq': 2}
2022-07-11 14:33:41,355 - DEBUG - Defaulting working directory to /home/saltfish/TestEnv
2022-07-11 14:33:41,366 - DEBUG - Sending Message: {"seq": 2, "type": "response", "request_seq": 2, "command": "runInTerminal", "body": {"processId": 506882}, "success": true}
2022-07-11 14:33:41,523 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'telemetry', 'output': 'VS/Diagnostics/Debugger/Launch', 'data': {'VS.Diagnostics.Debugger.ImplementationName': 'Microsoft.MIDebugEngine', 'VS.Diagnostics.Debugger.EngineVersion': '17.1.20405.1', 'VS.Diagnostics.Debugger.HostVersion': '17.1.20405.1', 'VS.Diagnostics.Debugger.AdapterId': 'cppdbg', 'VS.Diagnostics.Debugger.Launch.Duration': 217, 'VS.Diagnostics.Debugger.MIMode': 'gdb', 'VS.Diagnostics.Debugger.FrameworkVersion': '6.0.322.12309'}}, 'seq': 3}
2022-07-11 14:33:41,527 - DEBUG - Message received: {'type': 'response', 'request_seq': 1, 'success': True, 'command': 'launch', 'body': {}, 'seq': 4}
2022-07-11 14:33:41,533 - DEBUG - Message received: {'type': 'event', 'event': 'initialized', 'body': {}, 'seq': 5}
2022-07-11 14:33:42,103 - DEBUG - Sending Message: {"command": "setBreakpoints", "arguments": {"source": {"name": "test.cpp", "path": "/home/saltfish/TestEnv/test.cpp"}, "breakpoints": [{"line": 22}, {"line": 32}], "sourceModified": false}, "seq": 3, "type": "request"}
2022-07-11 14:33:42,104 - DEBUG - Sending Message: {"command": "setFunctionBreakpoints", "arguments": {"breakpoints": []}, "seq": 4, "type": "request"}
2022-07-11 14:33:42,105 - DEBUG - Sending Message: {"command": "setExceptionBreakpoints", "arguments": {"filters": []}, "seq": 5, "type": "request"}
2022-07-11 14:33:42,206 - DEBUG - Message received: {'type': 'response', 'request_seq': 3, 'success': True, 'command': 'setBreakpoints', 'body': {'breakpoints': [{'id': 1, 'verified': True, 'line': 22, 'BoundBreakpoints': []}, {'id': 2, 'verified': True, 'line': 32, 'BoundBreakpoints': []}]}, 'seq': 6}
2022-07-11 14:33:42,211 - DEBUG - Message received: {'type': 'event', 'event': 'breakpoint', 'body': {'reason': 'changed', 'breakpoint': {'id': 1, 'verified': True, 'line': 22, 'BoundBreakpoints': []}}, 'seq': 7}
2022-07-11 14:33:42,213 - DEBUG - Message received: {'type': 'event', 'event': 'breakpoint', 'body': {'reason': 'changed', 'breakpoint': {'id': 2, 'verified': True, 'line': 32, 'BoundBreakpoints': []}}, 'seq': 8}
2022-07-11 14:33:42,231 - DEBUG - Message received: {'type': 'response', 'request_seq': 4, 'success': True, 'command': 'setFunctionBreakpoints', 'body': {'breakpoints': []}, 'seq': 9}
2022-07-11 14:33:42,234 - DEBUG - Message received: {'type': 'response', 'request_seq': 5, 'success': True, 'command': 'setExceptionBreakpoints', 'body': {}, 'seq': 10}
2022-07-11 14:33:42,237 - DEBUG - Sending Message: {"command": "configurationDone", "seq": 6, "type": "request"}
2022-07-11 14:33:42,244 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': '=thread-group-added,id="i1"\nGNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2\nCopyright (C) 2020 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\nType "show copying" and "show warranty" for details.\nThis GDB was configured as "x86_64-linux-gnu".\nType "show configuration" for configuration details.\nFor bug reporting instructions, please see:\n<http://www.gnu.org/software/gdb/bugs/>.\nFind the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>.\n\nFor help, type "help".\nType "apropos word" to search for commands related to "word".\nRegistered pretty printers for UE classes\nWarning: Debuggee TargetArchitecture not detected, assuming x86_64.\n=cmd-param-changed,param="pagination",value="off"\n'}, 'seq': 12}
2022-07-11 14:33:42,253 - DEBUG - Message received: {'type': 'response', 'request_seq': 6, 'success': True, 'command': 'configurationDone', 'body': {}, 'seq': 11}
2022-07-11 14:33:42,254 - DEBUG - Sending Message: {"command": "threads", "seq": 7, "type": "request"}
2022-07-11 14:33:42,273 - DEBUG - Message received: {'type': 'response', 'request_seq': 7, 'success': True, 'command': 'threads', 'body': {'threads': []}, 'seq': 13}
2022-07-11 14:33:42,310 - DEBUG - Message received: {'type': 'event', 'event': 'process', 'body': {'startMethod': 'launch', 'name': '/home/saltfish/TestEnv/test', 'systemProcessId': 506891, 'pointerSize': 64}, 'seq': 14}
2022-07-11 14:33:42,310 - INFO - User Msg: The debuggee was started: /home/saltfish/TestEnv/test
2022-07-11 14:33:42,326 - DEBUG - Message received: {'type': 'event', 'event': 'thread', 'body': {'reason': 'started', 'threadId': 506891}, 'seq': 15}
2022-07-11 14:33:42,327 - DEBUG - Sending Message: {"command": "threads", "seq": 8, "type": "request"}
2022-07-11 14:33:42,330 - DEBUG - Message received: {'type': 'event', 'event': 'breakpoint', 'body': {'reason': 'changed', 'breakpoint': {'id': 1, 'verified': True, 'line': 22, 'BoundBreakpoints': []}}, 'seq': 16}
2022-07-11 14:33:42,333 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': 'Stopped due to shared library event (no libraries added or removed)\n'}, 'seq': 17}
2022-07-11 14:33:42,350 - DEBUG - Message received: {'type': 'response', 'request_seq': 8, 'success': True, 'command': 'threads', 'body': {'threads': [{'id': 506891, 'name': 'test [506891]'}]}, 'seq': 18}
2022-07-11 14:33:42,356 - DEBUG - Message received: {'type': 'event', 'event': 'breakpoint', 'body': {'reason': 'changed', 'breakpoint': {'id': 2, 'verified': True, 'line': 32, 'BoundBreakpoints': []}}, 'seq': 19}
2022-07-11 14:33:42,359 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'console', 'output': "Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.\n"}, 'seq': 20}
2022-07-11 14:33:42,378 - DEBUG - Message received: {'type': 'event', 'event': 'module', 'body': {'reason': 'new', 'module': {'id': 1, 'name': 'ld-linux-x86-64.so.2', 'path': '/lib64/ld-linux-x86-64.so.2', 'symbolFilePath': '/lib64/ld-linux-x86-64.so.2', 'vsLoadAddress': '140737353941248', 'vsPreferredLoadAddress': '140737353941248', 'vsModuleSize': 140676, 'vsLoadOrder': 0, 'vsTimestampUTC': '1649294681', 'vsIs64Bit': True}}, 'seq': 21}
2022-07-11 14:33:42,570 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': '\n'}, 'seq': 22}
2022-07-11 14:33:42,574 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': 'Breakpoint 1, main () at test.cpp:9\n'}, 'seq': 23}
2022-07-11 14:33:42,581 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': '9\t{\n'}, 'seq': 24}
2022-07-11 14:33:42,602 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'console', 'output': "Loaded '/usr/lib/x86_64-linux-gnu/libstdc++.so.6'. Symbols loaded.\n"}, 'seq': 25}
2022-07-11 14:33:42,610 - DEBUG - Message received: {'type': 'event', 'event': 'module', 'body': {'reason': 'new', 'module': {'id': 2, 'name': 'libstdc++.so.6', 'path': '/usr/lib/x86_64-linux-gnu/libstdc++.so.6', 'symbolFilePath': '/usr/lib/x86_64-linux-gnu/libstdc++.so.6', 'vsLoadAddress': '140737352393056', 'vsPreferredLoadAddress': '140737352393056', 'vsModuleSize': 951026, 'vsLoadOrder': 1, 'vsTimestampUTC': '1639008862', 'vsIs64Bit': True}}, 'seq': 26}
2022-07-11 14:33:42,610 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'console', 'output': "Loaded '/usr/lib/x86_64-linux-gnu/libgcc_s.so.1'. Symbols loaded.\n"}, 'seq': 27}
2022-07-11 14:33:42,615 - DEBUG - Message received: {'type': 'event', 'event': 'module', 'body': {'reason': 'new', 'module': {'id': 3, 'name': 'libgcc_s.so.1', 'path': '/usr/lib/x86_64-linux-gnu/libgcc_s.so.1', 'symbolFilePath': '/usr/lib/x86_64-linux-gnu/libgcc_s.so.1', 'vsLoadAddress': '140737351648736', 'vsPreferredLoadAddress': '140737351648736', 'vsModuleSize': 68197, 'vsLoadOrder': 2, 'vsTimestampUTC': '1622274567', 'vsIs64Bit': True}}, 'seq': 28}
2022-07-11 14:33:42,616 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'console', 'output': "Loaded '/usr/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.\n"}, 'seq': 29}
2022-07-11 14:33:42,620 - DEBUG - Message received: {'type': 'event', 'event': 'module', 'body': {'reason': 'new', 'module': {'id': 4, 'name': 'libc.so.6', 'path': '/usr/lib/x86_64-linux-gnu/libc.so.6', 'symbolFilePath': '/usr/lib/x86_64-linux-gnu/libc.so.6', 'vsLoadAddress': '140737349735984', 'vsPreferredLoadAddress': '140737349735984', 'vsModuleSize': 1526861, 'vsLoadOrder': 3, 'vsTimestampUTC': '1649294681', 'vsIs64Bit': True}}, 'seq': 30}
2022-07-11 14:33:42,621 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'console', 'output': "Loaded '/usr/lib/x86_64-linux-gnu/libm.so.6'. Symbols loaded.\n"}, 'seq': 31}
2022-07-11 14:33:42,625 - DEBUG - Message received: {'type': 'event', 'event': 'module', 'body': {'reason': 'new', 'module': {'id': 5, 'name': 'libm.so.6', 'path': '/usr/lib/x86_64-linux-gnu/libm.so.6', 'symbolFilePath': '/usr/lib/x86_64-linux-gnu/libm.so.6', 'vsLoadAddress': '140737348277184', 'vsPreferredLoadAddress': '140737348277184', 'vsModuleSize': 682984, 'vsLoadOrder': 4, 'vsTimestampUTC': '1649294681', 'vsIs64Bit': True}}, 'seq': 32}
2022-07-11 14:34:23,347 - DEBUG - Stop debug adapter with callback : self._Reset()
2022-07-11 14:34:23,348 - DEBUG - Sending Message: {"command": "disconnect", "arguments": {}, "seq": 9, "type": "request"}
2022-07-11 14:34:23,384 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': '\nProgram'}, 'seq': 33}
2022-07-11 14:34:23,387 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': ' received signal SIGTRAP, Trace/breakpoint trap.\n'}, 'seq': 34}
2022-07-11 14:34:23,395 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': '0x00007ffff7cb8fd2 in __GI___libc_read (fd=0, buf=0x5555566efec0, nbytes=8191) at ../sysdeps/unix/sysv/linux/read.c:26\n'}, 'seq': 35}
2022-07-11 14:34:23,401 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': 'Kill the program being debugged? (y or n) [answered Y; input not from terminal]\n'}, 'seq': 36}
2022-07-11 14:34:23,406 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': '[Inferior 1 (process 506891) killed]\n'}, 'seq': 37}
2022-07-11 14:34:23,410 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'console', 'output': "The program '/home/saltfish/TestEnv/test' has exited with code 0 (0x00000000).\r\n\n"}, 'seq': 38}
2022-07-11 14:34:23,413 - DEBUG - Message received: {'type': 'event', 'event': 'output', 'body': {'category': 'telemetry', 'output': 'VS/Diagnostics/Debugger/DebugCompleted', 'data': {'VS.Diagnostics.Debugger.ImplementationName': 'Microsoft.MIDebugEngine', 'VS.Diagnostics.Debugger.EngineVersion': '17.1.20405.1', 'VS.Diagnostics.Debugger.HostVersion': '17.1.20405.1', 'VS.Diagnostics.Debugger.AdapterId': 'cppdbg', 'VS.Diagnostics.Debugger.DebugCompleted.BreakCounter': 0}}, 'seq': 39}
2022-07-11 14:34:23,413 - DEBUG - Message received: {'type': 'response', 'request_seq': 9, 'success': True, 'command': 'disconnect', 'body': {}, 'seq': 40}
2022-07-11 14:34:23,414 - DEBUG - Setting server exit handler before disconnect
2022-07-11 14:34:23,436 - INFO - The server has terminated with status 0
2022-07-11 14:34:23,442 - DEBUG - Running server exit handler
2022-07-11 14:34:23,442 - INFO - Debugging complete.
2022-07-11 14:34:23,442 - DEBUG - Clearing down UI


```

### Vim version

```Text
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az32-74

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Neovim diagnostics

```Text
efmls-configs: require("efmls-configs.health").check()
========================================================================
  - OK: All checks passed

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - ERROR: Command timed out: curl -sL 'https://pypi.python.org/pypi/pynvim/json'
  - INFO: Python version: 3.8.10
  - INFO: pynvim version: 0.4.1
  - WARNING: Could not contact PyPI to get latest version.
  - ERROR: HTTP request failed: unable to get pypi response

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.19.3
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/saltfish/.cache/nvim/lsp.log
  - INFO: Log size: 157 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
```

### Operating System

Linux saltfish 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment] 2022-07-10 19:20
Repro steps are incomplete.

**Comment by puremourning** [comment] 2022-09-26 08:23
Sorry I still can't reproduce this, so let's close it. Having unreproducible bugs open is just noise. I don't doubt that there _is_ an issue here, so if you can find a reliable reproducer, happy to re-open.

**Closed by puremourning** 2022-09-26 08:23 UTC
Labels: bug, can't reproduce
