### ISSUE TITLE
Failed to set breakpoint when using symlinks

### ISSUE THREAD

**Issue by izhakjakov** [puremourning/vimspector#408] opened 2021-05-18 22:08 UTC
### Describe the bug

vimspector started giving me an error:
```
Unable to set breakpoint: Failed to set breakpoint: "{e}"
```
- I am using it with Go on NeoVIM on Darwin (MacOS)
- Trying to use it with the old configuration file that used to work
- Tried it with code that I was previously able to debug and it still giving me the error

### Possible culprit
It seems like the problem happens when starting vim in a symlink
I exited vim and did this:
```
cd $(realpath .)
```
Which took me to the physical address, then, I started vim again and this time the breakpoints worked.

### Minimal reproduciton

* Does your issue reproduce using `vim --clean -Nu /path/to/vimspector/support/minimal_vimrc` ? Yes
  * I do not have `vim` so I used:
  `nvim --clean -u ~/.config/nvim/plugged/vimspector/support/minimal_vimrc hello.go`
  _Notice nvim does not have `-N`_
* If you are using Neovim, does your issue reproduce using Vim?
    * I am using NeoVIM, and don't have vim configured with vimspector

#### List of steps to reproduce:
 1. Run `nvim --clean -u ~/.config/nvim/plugged/vimspector/support/minimal_vimrc hello.go`
2. Set breakpoint: `vimspector#ToggleBreakpoint()`
3. Launch vimspector: `vimspector#Launch()`
4. Getting: `Unable to set breakpoint: Failed to set breakpoint: "{e}"`

#### Use the following Vimspector config file:
```json
{
  "configurations": {
    "run": {
      "adapter": "vscode-go",
      "default": true,
      "configuration": {
        "request": "launch",
        "program": "${workspaceRoot}",
        "mode": "debug",
        "dlvToolPath": "$HOME/go/bin/dlv",
        "trace": true
      }
    }
  }
}
```

### Expected behaviour
* Set breakpoint
* Run until breakpoint
* No error message

### Actual behaviour
* Getting the error above
* No breakpoint is set
* Run until the end of program

#### Vimspector log:
```txt
2021-05-18 17:49:15,359 - INFO - **** INITIALISING NEW VIMSPECTOR SESSION ****
2021-05-18 17:49:15,359 - INFO - API is: neo
2021-05-18 17:49:15,359 - INFO - VIMSPECTOR_HOME = /Users/dt/.config/nvim/plugged/vimspector
2021-05-18 17:49:15,359 - INFO - gadgetDir = /Users/dt/.config/nvim/plugged/vimspector/gadgets/macos
2021-05-18 17:49:16,220 - INFO - User requested start debug session with {}
2021-05-18 17:49:16,222 - DEBUG - Reading configurations from: None
2021-05-18 17:49:16,222 - DEBUG - Reading configurations from: /CaseSensitive/repositories/Hello/.vimspector.json
2021-05-18 17:49:16,223 - DEBUG - Reading gadget config: /Users/dt/.config/nvim/plugged/vimspector/gadgets/macos/.gadgets.json
2021-05-18 17:49:16,225 - DEBUG - Reading gadget config: None
2021-05-18 17:49:16,225 - INFO - Configuration: {"adapter": "vscode-go", "default": true, "configuration": {"request": "launch", "program": "/CaseSensitive/repositories/Hello", "mode": "debug", "dlvToolPath": "/Users/dt/go/bin/dlv", "trace": true}}
2021-05-18 17:49:16,225 - INFO - Adapter: {"command": ["node", "/Users/dt/.config/nvim/plugged/vimspector/gadgets/macos/vscode-go/dist/debugAdapter.js"], "configuration": {"cwd": "/CaseSensitive/repositories/Hello"}, "name": "delve"}
2021-05-18 17:49:16,227 - DEBUG - min_width/height: 149/50, actual: 190/49 - result: horizontal
2021-05-18 17:49:16,259 - DEBUG - LAUNCH!
2021-05-18 17:49:16,261 - INFO - Starting debug adapter with: {"command": ["node", "/Users/dt/.config/nvim/plugged/vimspector/gadgets/macos/vscode-go/dist/debugAdapter.js"], "configuration": {"cwd": "/CaseSensitive/repositories/Hello"}, "name": "delve"}
2021-05-18 17:49:16,261 - DEBUG - Connection Type: neojob
2021-05-18 17:49:16,264 - INFO - Debug Adapter Started
2021-05-18 17:49:16,264 - DEBUG - Sending Message: {"command": "initialize", "arguments": {"adapterID": "delve", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true}, "seq": 0, "type": "request"}
2021-05-18 17:49:16,367 - DEBUG - Message received: {'seq': 1, 'type': 'response', 'request_seq': 0, 'command': 'initialize', 'success': True, 'body': {'supportsConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsSetVariable': True}}
2021-05-18 17:49:16,367 - DEBUG - Sending Message: {"command": "launch", "arguments": {"cwd": "/CaseSensitive/repositories/Hello", "request": "launch", "program": "/CaseSensitive/repositories/Hello", "mode": "debug", "dlvToolPath": "/Users/dt/go/bin/dlv", "trace": true, "name": "test"}, "seq": 1, "type": "request"}
2021-05-18 17:49:16,471 - DEBUG - Message received: {'seq': 2, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': "go: go.mod file not found in current directory or any parent directory; see 'go help modules'\n"}}
2021-05-18 17:49:16,476 - DEBUG - Message received: {'seq': 3, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': 'exit status 1\n'}}
2021-05-18 17:49:16,479 - DEBUG - Message received: {'seq': 4, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': 'Process exiting with code: 1\n'}}
2021-05-18 17:49:16,482 - DEBUG - Message received: {'seq': 5, 'type': 'response', 'request_seq': 1, 'command': 'launch', 'success': False, 'message': 'Failed to continue: Check the debug console for details.', 'body': {'error': {'id': 3000, 'format': 'Failed to continue: Check the debug console for details.', 'showUser': True}}}
2021-05-18 17:49:16,482 - ERROR - Request failed: Failed to continue: Check the debug console for details.
2021-05-18 17:49:16,483 - DEBUG - Message received: {'seq': 6, 'type': 'event', 'event': 'terminated'}
```

![image](https://user-images.githubusercontent.com/18270061/118730063-f5e90080-b804-11eb-9423-ac96cd2202d8.png)

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

#### Version of Vimspector:

`f4d756fe86a7a2ef86c86281e3d9dc7ba096feec`

#### Output of `:VimspectorDebugInfo`

```
Vimspector Debug Info
--------------------------------------------------------------------------------
ConnectionType: neojob
Adapter: 
--------------------------------------------------------------------------------
{
  "command": [
    "node",
    "/Users/dt/.config/nvim/plugged/vimspector/gadgets/macos/vscode-go/dist/debugAdapter.js"
  ],
  "configuration": {
    "cwd": "/CaseSensitive/repositories/Hello"
  },
  "name": "delve",
  "env": {},
  "cwd": "/CaseSensitive/repositories/Hello"
}
--------------------------------------------------------------------------------
Configuration: 
--------------------------------------------------------------------------------
{
  "adapter": "vscode-go",
  "default": true,
  "configuration": {
    "request": "launch",
    "program": "/CaseSensitive/repositories/Hello",
    "mode": "debug",
    "dlvToolPath": "/Users/dt/go/bin/dlv",
    "trace": true
  }
}
--------------------------------------------------------------------------------
API Prefix: neo
Launch/Init: False / False
Workspace Root: /CaseSensitive/repositories/Hello
Launch Config: 
--------------------------------------------------------------------------------
{
  "cwd": "/CaseSensitive/repositories/Hello",
  "request": "launch",
  "program": "/CaseSensitive/repositories/Hello",
  "mode": "debug",
  "dlvToolPath": "/Users/dt/go/bin/dlv",
  "trace": true,
  "name": "test"
}
--------------------------------------------------------------------------------
Server Capabilities: 
--------------------------------------------------------------------------------
{
  "supportsConditionalBreakpoints": true,
  "supportsConfigurationDoneRequest": true,
  "supportsSetVariable": true
}
--------------------------------------------------------------------------------

```

#### Output of `vim --version` or `nvim --version`

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/config -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4_2/share/nvim"

Run :checkhealth for more info
```

#### Output of `which vim` or `which nvim`:

```
/usr/local/bin/nvim
```

#### Output of `:py3 print( __import__( 'sys' ).version )`:

```
3.9.5 (default, May  4 2021, 03:36:27)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

* Output of `:py3 import vim`:

```
<No Output>
```

* Output of `:py3 import vimspector`:

```
<No Output>
```

#### For neovim: output of `:checkhealth`

```

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 32ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/local/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.5
  - INFO: pynvim version: 0.4.2 (outdated; from ~/Library/Python/3.9/lib/python/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v16.1.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```

#### Operating system: <linux or macOS> and version
  
```txt
 $〉sw_vers
ProductName:    macOS
ProductVersion: 11.3.1
```

#### I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md)
Yes

**Comment by puremourning** [comment] 2021-05-19 08:02
Thanks for the detailed report.

I don't see this in the log:

> Unable to set breakpoint: Failed to set breakpoint: "{e}"

Could you include a log for a working example ?

I do see this though:
 
> 2021-05-18 17:49:16,471 - DEBUG - Message received: {'seq': 2, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': "go: go.mod file not found in current directory or any parent directory; see 'go help modules'\n"}}

Don't know if relevant.

There was a vimspector change to do with using full paths for files a while ago, which might explain this, though I can't tell from the log what the problem is because it doesn't seem to include the err or message you're seeing.

**Comment by izhakjakov** [comment] 2021-05-19 12:53
Sorry about that, I did not realize that `dlv` does not work without `go.mod`

I redid it and got another error:
```txt
Protocol error: Server returned no threads
```
And the program just runs without stopping
![image](https://user-images.githubusercontent.com/18270061/118813642-59167980-b87d-11eb-8f76-8351d91be6c3.png)

#### Vimspector log:
```
2021-05-19 08:41:57,006 - INFO - **** INITIALISING NEW VIMSPECTOR SESSION ****
2021-05-19 08:41:57,006 - INFO - API is: neo
2021-05-19 08:41:57,007 - INFO - VIMSPECTOR_HOME = /Users/dt/.config/nvim/plugged/vimspector
2021-05-19 08:41:57,007 - INFO - gadgetDir = /Users/dt/.config/nvim/plugged/vimspector/gadgets/macos
2021-05-19 08:42:00,945 - INFO - User requested start debug session with {}
2021-05-19 08:42:00,947 - DEBUG - Reading configurations from: None
2021-05-19 08:42:00,947 - DEBUG - Reading configurations from: /CaseSensitive/repositories/Hello/.vimspector.json
2021-05-19 08:42:00,948 - DEBUG - Reading gadget config: /Users/dt/.config/nvim/plugged/vimspector/gadgets/macos/.gadgets.json
2021-05-19 08:42:00,949 - DEBUG - Reading gadget config: None
2021-05-19 08:42:00,949 - INFO - Configuration: {"adapter": "vscode-go", "default": true, "configuration": {"request": "launch", "program": "/CaseSensitive/repositories/Hello", "mode": "debug", "dlvToolPath": "/Users/dt/go/bin/dlv", "trace": true}}
2021-05-19 08:42:00,949 - INFO - Adapter: {"command": ["node", "/Users/dt/.config/nvim/plugged/vimspector/gadgets/macos/vscode-go/dist/debugAdapter.js"], "configuration": {"cwd": "/CaseSensitive/repositories/Hello"}, "name": "delve"}
2021-05-19 08:42:00,951 - DEBUG - min_width/height: 149/50, actual: 190/49 - result: horizontal
2021-05-19 08:42:00,987 - DEBUG - LAUNCH!
2021-05-19 08:42:00,989 - INFO - Starting debug adapter with: {"command": ["node", "/Users/dt/.config/nvim/plugged/vimspector/gadgets/macos/vscode-go/dist/debugAdapter.js"], "configuration": {"cwd": "/CaseSensitive/repositories/Hello"}, "name": "delve"}
2021-05-19 08:42:00,989 - DEBUG - Connection Type: neojob
2021-05-19 08:42:00,991 - INFO - Debug Adapter Started
2021-05-19 08:42:00,992 - DEBUG - Sending Message: {"command": "initialize", "arguments": {"adapterID": "delve", "clientID": "vimspector", "clientName": "vimspector", "linesStartAt1": true, "columnsStartAt1": true, "locale": "en_GB", "pathFormat": "path", "supportsVariableType": true, "supportsVariablePaging": false, "supportsRunInTerminalRequest": true}, "seq": 0, "type": "request"}
2021-05-19 08:42:01,124 - DEBUG - Message received: {'seq': 1, 'type': 'response', 'request_seq': 0, 'command': 'initialize', 'success': True, 'body': {'supportsConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsSetVariable': True}}
2021-05-19 08:42:01,125 - DEBUG - Sending Message: {"command": "launch", "arguments": {"cwd": "/CaseSensitive/repositories/Hello", "request": "launch", "program": "/CaseSensitive/repositories/Hello", "mode": "debug", "dlvToolPath": "/Users/dt/go/bin/dlv", "trace": true, "name": "test"}, "seq": 1, "type": "request"}
2021-05-19 08:42:01,427 - DEBUG - Message received: {'seq': 2, 'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': 'API server listening at: 127.0.0.1:43642\n'}}
2021-05-19 08:42:01,637 - DEBUG - Message received: {'seq': 3, 'type': 'event', 'event': 'initialized'}
2021-05-19 08:42:01,638 - DEBUG - Sending Message: {"command": "setBreakpoints", "arguments": {"source": {"name": "hello.go", "path": "/CaseSensitive/repositories/Hello/hello.go"}, "breakpoints": [{"line": 6}]}, "sourceModified": false, "seq": 2, "type": "request"}
2021-05-19 08:42:01,639 - DEBUG - Message received: {'seq': 4, 'type': 'response', 'request_seq': 1, 'command': 'launch', 'success': True}
2021-05-19 08:42:01,795 - DEBUG - Message received: {'seq': 5, 'type': 'response', 'request_seq': 2, 'command': 'setBreakpoints', 'success': False, 'message': 'Failed to set breakpoint: "{e}"', 'body': {'error': {'id': 2002, 'format': 'Failed to set breakpoint: "{e}"', 'variables': {'e': "TypeError: Cannot read property '0' of undefined"}, 'showUser': True}}}
2021-05-19 08:42:01,795 - ERROR - Request failed: Failed to set breakpoint: "{e}"
2021-05-19 08:42:01,796 - WARNING - User Msg: Unable to set breakpoint: Failed to set breakpoint: "{e}"
2021-05-19 08:42:01,796 - DEBUG - Sending Message: {"command": "configurationDone", "seq": 3, "type": "request"}
2021-05-19 08:42:01,798 - DEBUG - Message received: {'seq': 6, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': '{}\n'}}
2021-05-19 08:42:01,804 - DEBUG - Message received: {'seq': 7, 'type': 'response', 'request_seq': 3, 'command': 'configurationDone', 'success': True}
2021-05-19 08:42:01,804 - DEBUG - Sending Message: {"command": "threads", "seq": 4, "type": "request"}
2021-05-19 08:42:01,804 - DEBUG - Message received: {'seq': 8, 'type': 'event', 'event': 'output', 'body': {'category': 'stdout', 'output': 'Hello\n\nWorld!\n'}}
2021-05-19 08:42:01,807 - DEBUG - Message received: {'seq': 9, 'type': 'event', 'event': 'terminated'}
2021-05-19 08:42:01,809 - DEBUG - Message received: {'seq': 10, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': 'Failed to get state - Process 53488 has exited with status 0\n'}}
2021-05-19 08:42:01,813 - DEBUG - Message received: {'seq': 11, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': 'dumpStacktrace - Failed to get debugger state Process 53488 has exited with status 0\n'}}
2021-05-19 08:42:01,816 - DEBUG - Message received: {'seq': 12, 'type': 'response', 'request_seq': 4, 'command': 'threads', 'success': True, 'body': {'threads': []}}
2021-05-19 08:42:01,817 - INFO - User Msg: Protocol error: Server returned no threads
2021-05-19 08:42:01,818 - DEBUG - Message received: {'seq': 13, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': 'dumpStacktrace: Failed to produce stack traceProcess 53488 has exited with status 0\n'}}
2021-05-19 08:42:07,921 - DEBUG - Stop debug adapter with no callback
2021-05-19 08:42:07,923 - DEBUG - Sending Message: {"command": "disconnect", "arguments": {}, "seq": 5, "type": "request"}
2021-05-19 08:42:07,926 - DEBUG - Message received: {'seq': 14, 'type': 'response', 'request_seq': 5, 'command': 'disconnect', 'success': True}
2021-05-19 08:42:07,929 - DEBUG - Message received: {'seq': 15, 'type': 'event', 'event': 'output', 'body': {'category': 'stderr', 'output': 'Process exiting with code: 0\n'}}
2021-05-19 08:42:07,934 - DEBUG - Message received: {'seq': 16, 'type': 'event', 'event': 'terminated'}
2021-05-19 08:42:08,038 - INFO - The server has terminated with status 0
2021-05-19 08:42:08,044 - DEBUG - No server exit handler
```

#### :VimspectorDebugInfo
```
Vimspector Debug Info
--------------------------------------------------------------------------------
ConnectionType: neojob
Adapter: 
--------------------------------------------------------------------------------
{
  "command": [
    "node",
    "/Users/dt/.config/nvim/plugged/vimspector/gadgets/macos/vscode-go/dist/debugAdapter.js"
  ],
  "configuration": {
    "cwd": "/CaseSensitive/repositories/Hello"
  },
  "name": "delve",
  "env": {},
  "cwd": "/CaseSensitive/repositories/Hello"
}
--------------------------------------------------------------------------------
Configuration: 
--------------------------------------------------------------------------------
{
  "adapter": "vscode-go",
  "default": true,
  "configuration": {
    "request": "launch",
    "program": "/CaseSensitive/repositories/Hello",
    "mode": "debug",
    "dlvToolPath": "/Users/dt/go/bin/dlv",
    "trace": true
  }
}
--------------------------------------------------------------------------------
API Prefix: neo
Launch/Init: True / True
Workspace Root: /CaseSensitive/repositories/Hello
Launch Config: 
--------------------------------------------------------------------------------
{
  "cwd": "/CaseSensitive/repositories/Hello",
  "request": "launch",
  "program": "/CaseSensitive/repositories/Hello",
  "mode": "debug",
  "dlvToolPath": "/Users/dt/go/bin/dlv",
  "trace": true,
  "name": "test"
}
--------------------------------------------------------------------------------
Server Capabilities: 
--------------------------------------------------------------------------------
{
  "supportsConditionalBreakpoints": true,
  "supportsConfigurationDoneRequest": true,
  "supportsSetVariable": true
}
--------------------------------------------------------------------------------
```

#

### Expected Behaviour
If I do `cd $(realpath .)` and then run it stops at the breakpoint as expected:  

![image](https://user-images.githubusercontent.com/18270061/118814252-f1acf980-b87d-11eb-8d04-721a6d019efd.png)

**Comment by puremourning** [comment] 2021-05-19 21:19
Ok now we’re getting somewhere. I see this. 

> False, 'message': 'Failed to set breakpoint: "{e}"', 'body': {'error': {'id': 2002, 'format': 'Failed to set breakpoint: "{e}"', 'variables': {'e': "TypeError: Cannot read property '0' of undefined"}, 'showUser': True}}}

the debug adapter is crashing due to a TypeError. 

This is usually caused by a missing launch parameter. 

I have go tests in my CI so can you try the example project in support/test ? Does that work?

**Comment by izhakjakov** [comment] 2021-05-20 17:24
I do not exhibit any problems using **your** example and noticed that **your** `.vimspector.json` is using the filename for the `program` field  

So I modified **my original** `.vimspector.json` to use `"program": "${workspaceRoot}/hello.go"` instead of `"program": "${workspaceRoot}`
```json
{
  "configurations": {
    "run": {
      "adapter": "vscode-go",
      "default": true,
      "configuration": {
        "request": "launch",
        "program": "${workspaceRoot}/hello.go",
        "mode": "debug",
        "dlvToolPath": "$HOME/go/bin/dlv",
        "trace": true
      }
    }
  }
}
```
And now I do not exhibit any problems using **my original** example either.

**Comment by puremourning** [comment] 2021-05-20 18:14
Ok closing then. Issue was in the launch config.

**Comment by puremourning** [comment] 2021-05-20 18:15
Actually wait. Maybe there is still some symlink shenanigans worth double checking.

**Comment by izhakjakov** [comment] 2021-05-20 19:21
Well I think it's suppose to work without specifying the filename since go program are technically the directory

Also why would it work with the realpath but not the link?

**Comment by puremourning** [comment] 2021-05-20 19:23
I don’t know, but I would be surprised if this was a vimspector issue as opposed to a delve or debug adapter issue.

**Comment by izhakjakov** [comment] 2021-05-20 20:31
Well you would know better than me.  I can help investigate but need guidance.

**Comment by puremourning** [comment] 2021-05-20 20:56
DAP doesn’t seem say anything about symlinks. And what vmspector is sending seems to be self consistent, ie always full paths staring with /CaseSensitive/repositories/Hello. So maybe a bug in the adapter. One way to check is to see if you get the same behaviour in other clients not like vscode. Sorry I don’t have capacity to chase this down right now.

**Comment by izhakjakov** [comment] 2021-05-20 21:18
No worries it is not critical since there is a workaround and if someone else is searching for a solution he might find this report and figure out what to do.

**Comment by izhakjakov** [comment] 2021-06-04 21:33
I found another issue when using a replace with a symlink vs realpath in a go module (`go.mod`)  

## For example:
### symlink
```
module github.com/dtools/csd-utils

go 1.13

replace github.com/swaywm/sway => /Users/dt/Repositories/sway.master 
```
Getting the error:
```
Unable to set breakpoint: Failed to set breakpoint: "{e}"
```
### realpath
```
module github.com/dtools/csd-utils

go 1.13

replace github.com/swaywm/sway => /CaseSensitive/repositories/sway.master 
```
works as expected.  

  ---
I am guessing this is related  

<sup>All the settings described in this issue body are the same</sup>

**Comment by izhakjakov** [comment] 2021-06-04 21:38
I dealing with some parallel goroutines and initially thought the debugger cannot handle this but actually besides this bug the debugger works fine :)
It drove me crazy till I realized it could be the `go.mod` 🤦

**Comment by puremourning** [comment] 2021-09-05 20:36
has it been confirmed that this is a issue unique to vimspector, vs being a problem with the debug adapter?

**Comment by izhakjakov** [comment] 2021-09-07 16:01
hmm...
I'll have updated `vimspector` as well as `delve` multiple times so I can try reproducing and see if the error still persists.
If it still is, then I'll try using delve CLI and let you know.

If you want me try something else, lmk.

**Comment by izhakjakov** [comment] 2021-09-07 19:47
Confirmed that this is still failing with current Vimspector:
```
$〉git -C /Users/dt/.config/nvim/plugged/vimspector rev-parse HEAD
51d78fce5f95fb10ba84b8ab66e97d44d75df010
```
New errmsg: `Protocol error: Server returned no threads`
Still working fine with workaround: `cd $(realpath .)`

But not reproducible with pure `delve`
```
$〉dlv debug
Type 'help' for list of commands.
(dlv) break ./hello.go:6
Breakpoint 1 set at 0x10aba38 for main.main() ./hello.go:6
(dlv) breakpoints
Breakpoint runtime-fatal-throw (enabled) at 0x1032840 for runtime.throw() /usr/local/opt/go/libexec/src/runtime/panic.go:1188 (0)
Breakpoint unrecovered-panic (enabled) at 0x1032ba0 for runtime.fatalpanic() /usr/local/opt/go/libexec/src/runtime/panic.go:1271 (0)
        print runtime.curg._panic.arg
Breakpoint 1 (enabled) at 0x10aba38 for main.main() ./hello.go:6 (0)
(dlv) continue
> main.main() ./hello.go:6 (hits goroutine(1):1 total:1) (PC: 0x10aba38)
     1: package main
     2:
     3: import "fmt"
     4:
     5: func main() {
=>   6:         fmt.Println(`hello`)
     7:         fmt.Println()
     8:         fmt.Println(`world`)
     9: }
(dlv) continue
hello

world
Process 58822 has exited with status 0
(dlv) q
```

**Comment by izhakjakov** [comment] 2021-09-07 19:51
> has it been confirmed that this is a issue unique to vimspector, vs being a problem with the debug adapter?

Have I answered your question?  Or did you want me to try this with vs-code?

**Comment by puremourning** [comment] 2021-09-07 20:12
Yeah sorry the question was does the same project work with vscode ?

**Comment by izhakjakov** [comment] 2021-09-07 20:23
I never got around to try it on vscode.  Never actually used it as a debbuger just for html, markdown, etc ...

I'll will try on the weekend if I find the time

**Comment by puremourning** [comment] 2021-12-30 18:11
Go debugging has switched to delve now, if this is still an issue, we can raise a new issue with up to date diagnostics.

**Closed by puremourning** 2021-12-30 18:11 UTC

**Comment by izhakjakov** [comment] 2022-01-02 12:47
I have been using delve all along but I was not aware of this `property`. Seems quite stupid to me but maybe there is a reason behind this that I don't know about.

Anyways, this solution works. Thank you very much!
(and a happy new year 🥳)

**Comment by izhakjakov** [comment] 2022-01-02 13:11
Actually, I have been using delve all along. Still not working :/

I tried using:
```json
"substitutePath": [
	{
		"from": "/Users/dt/Repositories/Hello",
		"to": "/CaseSensitive/repositories/Hello"
	}
]
```
```json
"substitutePath": [
	{
		"from": "~/Repositories/Hello",
		"to": "/CaseSensitive/repositories/Hello"
	}
]
```
```json
"substitutePath": [
	{
		"from": "$HOME/Repositories/Hello",
		"to": "/CaseSensitive/repositories/Hello"
	}
]
```

Anyways, happy new year 🥳
