### ISSUE TITLE
Vimspector unavailable: Requires Vim compiled with Python 3.6

### ISSUE THREAD

**Issue by mmorse1217** [puremourning/vimspector#568] opened 2022-04-01 17:38 UTC
### Description

I'm trying to set up Vimspector, but I have definitely compiled vim with Python > 3.6 (3.6.9). I've compiled vim with several different versions of Python greater than 3.6 and I'm still getting this error. I'm inside of a Ubuntu 18.04 docker container, so I'm fairly certain there is no contamination with other python3 versions (python2.7 is also installed but I'm not configuring vim with python2 here). The only issue I could find about this was [here](https://github.com/puremourning/vimspector/issues/396), but it was closed due to lack of info. Please let me know if there is any additional information that I can provide to aid in the debugging process.

Thanks very much!

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Minimal Reproduction

List of steps to reproduce:
I'm using vim-plug so the minimal `.vimrc` looks like 
```
call plug#begin('~/.vim/plug-plug')
Plug 'puremourning/vimspector'
call plug#end()
```
1. Run `vim -Nu /path/to/vimspector/support/minimal_vimrc`
2. Run `:VimspectorInstall debugpy` or any other Vimspector command
3. Press _this sequence of keys_

### Expected Behaviour

Debugpy begins installing (or whatever the corresponding command does begins)

### Actual Behaviour

```
Exception while loading vimspector: Vim(py3):UnicodeEncodeError: 'latin-1' codec can't encode character '\u25cf' in position 0: ordinal not in range(256) 
From: function vimspector#Install[1]..<SNR>23_Enabled[2]..vimspector#internal#state#Reset, line 3 Vimspector unavailable: Requires Vim compiled with Python 3.6
Press ENTER or type command to continue
```

### Additional information

I'm building Vim 8.2 from source with the following configuration:
```
./configure --with-features=huge \
            --enable-multibyte \
            --enable-python3interp=yes \
            --with-python3-command=python3 \
            --with-python3-config-dir=$(python3-config --configdir) \
            --enable-gui=gtk2 \
            --enable-cscope \
            --enable-terminal  \
            --enable-fail-if-missing  \
            --prefix=/usr/local
```

I'm building vim inside of an Ubuntu 18.04 Docker container. I'm using vim-plug as a plugin manager.

### Installation Type

Plugin Manager (git clone)

### Vimspector version

e4b5c76b9c9e333f7cdc853af42e7ef12a1d5e58

### Debug Info

```Text
Exception while loading vimspector: Vim(py3):UnicodeEncodeError: 'latin-1' codec can't encode character '\u25cf' in position 0: ordinal not in range(256) 
From: function vimspector#Install[1]..<SNR>23_Enabled[2]..vimspector#internal#state#Reset, line 3 Vimspector unavailable: Requires Vim compiled with Python 3.6
Press ENTER or type command to continue
```
```


### Log file

```Text
2022-04-01 17:30:43,483 - INFO - **** INITIALISING NEW VIMSPECTOR SESSION ****                                                          2022-04-01 17:30:43,483 - INFO - API is:                                                                                                
2022-04-01 17:30:43,483 - INFO - VIMSPECTOR_HOME = /root/.vim/plug-plug/vimspector/python3/vimspector/../..                             
2022-04-01 17:30:43,487 - INFO - gadgetDir = /root/.vim/plug-plug/vimspector/gadgets/linux
```

### Vim version

```Text
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  1 2022 16:54:44)
Included patches: 1-4662
Compiled by root@4a1ae94aa4b0
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
 f-b for $VIMRUNTIME: "/usr/local/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lcanberra -ldl -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm
```

### Python version

3.6.9 (default, Mar 15 2022, 13:55:28) [GCC 8.4.0]

### Operating System

Linux 4a1ae94aa4b0 5.4.0-99-generic #112~18.04.1-Ubuntu SMP Thu Feb 3 14:09:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment] 2022-04-01 17:58
does it work if you do `set encoding=utf-8` ?

**Comment by mmorse1217** [comment] 2022-04-01 18:25
Nope :( same error

**Comment by puremourning** [comment] 2022-04-01 18:27
Can you prove full steps to repro using a Ubuntu 18.04 container ? Yours steps above say vim plug which is by definition not minimal. Prefer using the instructions in CONTRIBUTING.md to run with the supplied minimal vimrc. 

It’s very odd that Latin-1 is happening outside of windows.

**Comment by puremourning** [comment] 2022-04-01 18:28
Naturally I can’t repro btw. That’s why I’m asking.

**Comment by mmorse1217** [comment] 2022-04-01 18:32
Sorry, I was unclear there; that's my mistake. I'm able to reproduce the error with the minimal_vimrc as requested in CONTRIBUTING.md; I just forgot to delete the mention of using vim-plug. 

I'll post a Dockerfile to repro the error.

**Comment by puremourning** [comment] 2022-04-01 18:36
Great thanks. I wonder if it’s like some non ASCII character in some path somewhere or in the environment or something. Basically what’s happening is importing vimspector is failing with that Unicode error but I’m not sure where it’s coming form.

**Comment by puremourning** [comment] 2022-04-01 18:37
Also I take it :py3 pass works and produces no output?

**Comment by mmorse1217** [comment] 2022-04-01 18:39
Yes, `:py3 pass` works no problem. It also works when importing the version of python above.

**Comment by puremourning** [comment] 2022-04-01 19:07
Thanks, trying now

**Comment by puremourning** [comment] 2022-04-01 19:10
OK well it does work for me if I `:set encoding=utf-8`

**Comment by puremourning** [comment] 2022-04-01 19:17
Thanks for the help reproducing this!
It's down to the locale:

```
root@1d0f3ba3c743:/~# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

This can be solved by setting the locale to a UTF-8 one, like I do in my CI container:

https://github.com/puremourning/vimspector/blob/master/tests/ci/image/Dockerfile#L4

Due to fussy and annoying python reasons I don't have a lot of patience to try and make all these encoding issues work. I'm kinda just supporting utf-8 TBH because it's too much work for little old me to handle all many encodings.

---


FWIW you still get a failure due to not having python setuptools installed, which is required to work with debugpy. Fixed by `apt install python3-pip`: https://github.com/puremourning/vimspector/blob/master/tests/ci/image/Dockerfile#L20

**Closed by puremourning** 2022-04-01 19:17 UTC

**Comment by mmorse1217** [comment] 2022-04-01 19:36
You are my savior!! Thank you so much for taking the time to figure this out! Changing the locale worked and installing `python3-pip` fixed the `debugpy` install issue.  I never would have thought to look at the locale... You saved me a ton of time!
