### ISSUE TITLE
[Feature Request]: Syntax highlighting to separate variable names from values

### ISSUE THREAD

**Issue by raiguard** [puremourning/vimspector#324] opened 2020-12-21 23:29 UTC
My apologies if this has been requested already, but I couldn't find anything on it.

**Is your feature request related to a problem? Please describe.**
Attempting to distinguish variable names from their values in the variables / watch panels is difficult.

**Describe the solution you'd like**
Coloring the names separate from the values would greatly help with this issue. Bonus points for coloring string vs int vs object values differently (like vscode).

**Additional context**
Here is the same breakpoint in vimspector (neovim) and vscode. For me, the vscode variables are significantly easier to read than the vimspector variables.

![image](https://user-images.githubusercontent.com/3515394/102831659-91d32500-43a9-11eb-92df-44878a6f7a16.png)
![image](https://user-images.githubusercontent.com/3515394/102831631-867ff980-43a9-11eb-948a-38d9abcca119.png)

**Comment by puremourning** [comment] 2021-01-08 16:31
what is the filetype of the file that's being debugged ?

vimspector sets the syntax of the watch and variables windows to match the filetype being debugged. this isn't perfect but it's not awful either. Though in your screenshot it doesn't look like that worked. Can you make a repro case, per CONTRIBUTING.md ?

There's no simple way to have a syntax file that matches what vimspector displays in those windows for those bits and the debugged language for the values. It's quite a lot of work and I'm not sure I have the bandwidth for it.

**Comment by puremourning** [comment] 2021-02-06 21:31
No answer, so closing.

**Closed by puremourning** 2021-02-06 21:31 UTC

**Comment by raiguard** [comment] 2021-02-06 21:40
Oh, my apologies, I completely missed the notification that you had replied. I will get back to you this weekend.

**Comment by raiguard** [comment] 2021-02-09 07:22
Upon cursory inspection, I believe the problem is that I'm using treesitter for my syntax highlighting. If I disable treesitter, then the variables view gets _some_ syntax highlighting to match the basic syntax highlighting of the file.

Would you like me to file a proper bug report for this? This seems more like a future compatibility thing rather than an actual bug.

**Comment by puremourning** [comment] 2021-02-09 08:06
I guess the problem is that the buffer is not really valid syntax so treesitter can’t parse it to make a CST. I don’t have a solution for that. Is there a way to turn off tree sitter per buffer? If it were trivial I would consider a PR that did that, but otherwise I’m unlikely have any time to look at this.
