### ISSUE TITLE
bash debugger always pass an "undefined" argument

### ISSUE THREAD

**Issue by zerobikappa** [puremourning/vimspector#766] opened 2023-04-30 18:41 UTC
### Description

the arguments was always appended with a "undefined" string.

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Sample project works?

Reproducable with sample project

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc ....`
2. Open any of bash script
3. Press <F5> to start debug
4. add a WATCH to "$@", and view the value of "$@"

### Expected Behaviour

`$@` should only include the arguments which I set in `"args": []`.
For example, if I set `"args": ["1", "2", "3", "4"]` in `.vimspector.json`,
`$@` should be `1 2 3 4`.

### Actual Behaviour

the arguments was always appended with a "undefined" string.
For example, `echo "$@"` would show `1 2 3 4 undefined`

### Installation Type

Plugin Manager (git clone)

### Vimspector version

3321e47c6f71258084c60d2887abfb946d3b6bdd

### Vim version

```Text
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 21 2023 20:51:42)
Included patches: 1-1420
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl/dyn
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        +lua/dyn           +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -pthread -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/vim/src=/usr/src/debug/vim -flto=auto -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -L/usr/local/lib -o vim -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lcanberra -lacl -lattr -lgpm -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.36/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```

### Operating System

archlinux

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment] 2023-04-30 19:16
Please provide vimspector log as requested.

**Comment by zerobikappa** [comment] 2023-04-30 20:27
> Please provide vimspector log as requested.

run command:
```
cd ~/.vim/pack/vimspector/opt/vimspector/support/test/
./run_test_vim bash/test_script
```
1) [output debug info](https://paste2.org/6MdEdJF8)
2) [vimspector log](https://paste2.org/BPfjfphB)

**Comment by puremourning** [comment] 2023-04-30 21:21
Thanks. As can be seen from the log, vimspector is correctly sending the args as specified

> debug_adapter_connection.py:205 - 0 - Sending Message: {"command": "launch", "arguments": {"args": ["1", "2", "3"], "cwd": 

Therefore this issue is in the debug adapter, not vimspector, so there's not much I can do.

**Comment by puremourning** [comment] 2023-05-01 09:05
I can reproduce this btw. 

It seems that the bash debug adapter hasn't been touched for nearly 5 years, so maybe it's just abandonware at this point, but it might be worth raising an issue there.

FWIW I can see that the debug adapter itself specified the 'undefined' argument, in the `runInTerminal` request to Vimspector:

```
2023-05-01 10:01:01,248 - DEBUG - debug_adapter_connection.py:266 - 0 - Message received: {'command': 'runInTerminal', 'arguments': {'kind': 'integrated', 'title': 'Bash Debug Console', 'cwd': '.', 'args': ['/opt/homebrew/opt/bash/bin/bash', '-c', 'cd "/Users/ben/.vim/bundle/vimspector"; while [[ ! -p "/tmp/vscode-bash-debug-fifo-10355" ]]; do sleep 0.25; done; "/opt/homebrew/opt/bash/bin/bash" "/Users/ben/.vim/vimspector-conf/gadgets/macos/vscode-bash-debug/bashdb_dir/bashdb" --quiet --tty "/tmp/vscode-bash-debug-fifo-10355" --tty_in "/tmp/vscode-bash-debug-fifo-10355_in" --library "/Users/ben/.vim/vimspector-conf/gadgets/macos/vscode-bash-debug/bashdb_dir" -- "/Users/ben/.vim/bundle/vimspector/test.sh" foo bar baz undefined']}, 'type': 'request', 'seq': 2}
```

Quoting the relevant part:

> `-- "/Users/ben/.vim/bundle/vimspector/test.sh" foo bar baz undefined']}, '`

**Comment by puremourning** [comment] 2023-05-01 09:10
Actually I read the bash debug adapter code. it looks like there is a mandatory (pointless!) argument. I'll fix it in vimspector to work around.

**Comment by puremourning** [comment] 2023-05-01 09:16
Thanks for the report. Fix is in CI.

**Closed** 2023-05-01 10:03 UTC
Labels: Upstream
