### ISSUE TITLE
Breakpoints problem on Window-OS

### ISSUE THREAD

**Issue by NDK2020** [puremourning/vimspector#314] opened 2020-12-04 09:05 UTC
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug
I can normally debug the program with breakpoints as the first time but the later time it won't stop at breakpoints anymore.
I have to close Vim and reopen to debug again.
I'm using Vim 8.2, 

> Provide A clear and concise description of what the bug is.

### Minimal reproduciton

> Please answer the following questions

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc` ? \[Yes/No] No
* If you are using Neovim, does your issue reproduce using Vim? \[Yes/No] I don't use Neovim

> List of steps to reproduce:

> 1. Run `vim -Nu /path/to/vimspector/support/minimal_vimrc`
> 2. Open _this project_...
> 3. Press _this sequence of keys_

> Use the following Vimspector config file:

```
paste .vimspector.json here
{
  "configurations": {
    "Python: Attach To Vim": {
      "variables": {
        "port": "5678",
        "host": "localhost"
      },
      "adapter": "vscode-cpptools",
      "configuration": {
        "request": "attach"
      }
    },
    "Python: Run current script": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "program": "${file}",
        "args": [ "*${args:--update-gadget-config}" ],
        "justMyCode#json": "${justMyCode:true}"
      }
    },
    "CPP: Run current script": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "request": "launch",
        "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "args": [ "*${args:--update-gadget-config}"],
        "justMyCode#json": "${justMyCode:true}"
      }
    }
  }
}


### Expected behaviour

> Provide A clear and concise description of what you expected to happen.
int main () {
...
//toggle breakpoint line 75
...
}
Expected behaviour is re-run the program with breakpoints

### Actual behaviour
The first time the debugger stop at line 75, the second won't

> What actually happened, including output, log files etc.

> Please include:
> * Vimspector log (~/.vimspector.log)
> * Output from any or all UI diagnostic tabs (Server, etc.)

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue. --> Sorry I'm newbie don't know how much
to use git. So I hope there is a solution for my case here

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)
I've just cloned vimspector via git yesterday

* Output of `vim --version` or `nvim --version`

```
paste here
```

* Output of `which vim` or `which nvim`:

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 24 2020 22:03:08)
MS-Windows 64-bit console version
Included patches: 1-633
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.  Features included (+) or not (-):
+acl                +ex_extra           +multi_lang         +tcl/dyn
+arabic             +extra_search       +mzscheme/dyn       +termguicolors
+autocmd            -farsi              -netbeans_intg      +terminal
+autochdir          +file_in_path       +num64              -termresponse
+autoservername     +find_in_path       +packages           +textobjects
-balloon_eval       +float              +path_extra         +textprop
+balloon_eval_term  +folding            +perl/dyn           -tgetent
-browse             -footer             +persistent_undo    +timers
++builtin_terms     +gettext/dyn        +popupwin           +title
+byte_offset        -hangul_input       -postscript         -toolbar
+channel            +iconv/dyn          +printer            +user_commands
+cindent            +insert_expand      +profile            +vartabs
+clientserver       +ipv6               +python/dyn         +vertsplit
+clipboard          +job                +python3/dyn        +virtualedit
+cmdline_compl      +jumplist           +quickfix           +visual
+cmdline_hist       +keymap             +reltime            +visualextra
+cmdline_info       +lambda             +rightleft          +viminfo
+comments           +langmap            +ruby/dyn           +vreplace
+conceal            +libcall            +scrollbind         +vtp
+cryptv             +linebreak          +signs              +wildignore
+cscope             +lispindent         +smartindent        +wildmenu
+cursorbind         +listcmds           +sound              +windows
+cursorshape        +localmap           +spell              +writebackup
+dialog_con         +lua/dyn            +startuptime        -xfontset
+diff               +menu               +statusline         -xim
+digraphs           +mksession          -sun_workshop       -xpm_w32
-dnd                +modify_fname       +syntax             -xterm_save
-ebcdic             +mouse              +tag_binary
+emacs_tags         -mouseshape         -tag_old_static
+eval               +multi_byte_ime/dyn -tag_any_white
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python38.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DRUBY_VERSION=24 -DFEAT_HUGE /Fd.\ObjCULYHTRZAMD64/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python38.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib /PDB:vim.pdb -debug

* Output of `:py3 print( __import__( 'sys' ).version )`:

3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 but (AMD64)]

* Output of `:py3 import vim`:

```
Nothing shown
```

* Output of `:py3 import vimspector`:

```
Nothing shown
```


* For neovim: output of `:checkhealth`

```
Nothing shown
```

* Operating system: <linux or macOS> and version
  Window 10 home
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes/No] yes


### Additional information

Add any other context about the problem here.

**Comment by puremourning** [comment] 2020-12-05 15:57
I don't see a clear set of steps to reproduce.

**Comment by NDK2020** [comment] 2020-12-13 11:07
Dear,

Really sorry for late response.
I have recorded my screen, hope that will help.
You can watch the process via this link: https://www.youtube.com/watch?v=6_5SL9ppsWA


Thanks & Best Regards,

Khoa Nguyen Dang


________________________________

**Comment by puremourning** [comment] 2021-01-09 10:28
Closing as I can't reproduce it.

**Closed by puremourning** 2021-01-09 10:28 UTC
Labels: can't reproduce
